# Generated by Django 4.0.2 on 2022-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=500)),
                ('back_text', models.CharField(max_length=500)),
                ('example_text', models.CharField(max_length=500)),
                ('last_revisited_date', models.DateTimeField(verbose_name='data_revisited')),
            ],
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flashcards', models.ManyToManyField(to='flashcard.Flashcard')),
            ],
        ),
    ]
