# Generated by Django 4.0.2 on 2022-04-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDeck',
            new_name='StudyDeck',
        ),
    ]
